= Wrapping Up

In this quick start section you created your first Angular Application!

You should now have at least a top-level view of what an Angular application is, how it functions and how to go about architecting it.

We covered:


Environment:: How to use link:stackblitz.com[stackblitz.com] to write Angular apps in a browser
Components:: Which let us extend the HTML language to create new tags and forms the basis of an Angular application.
Bootstrapping:: How to actually make Angular load and take control of a HTML page.
Binding:: String interpolation with `{{ }}` and both input property binding as well as output event binding.
NgFor:: How to render multiple elements using the built-in `NgFor` *directive*.
Data Modelling:: We touched on *data modelling*, by creating our own Joke class which encapsulated all our data and logic relate to a joke.
Template Local Variables:: Capturing user input from users by adding `#` variables to input controls.
Architecture:: We started to see how we go about building Angular apps by wiring together _inputs_ and _outputs_ in order to glue Components together.

We'll be going into _much_ more detail into each of these topics, and others, in future chapters.

However since Angular is based on TypeScript it makes sense to get a good understanding of those features before we dive into the rest of this course so that's the topic of the next section.
