---
lecture_video: JvhLKqHksvU
---
:sourcedir: {docdir}/content/{filedir}/code
:toc:
= Testing Dependency Injection

== Learning Objectives

* Know how we can configure the injectors for testing in our Angular application.
* Know the various methods we can use to resolve tokens for testing.

== Resolving via `TestBed`

This is how we've injected dependencies so far in this section.

The `TestBed` acts as a dummy Angular Module and we can configure it like one including with a set of providers like so:

[source,typescript]
----
TestBed.configureTestingModule({
  providers: [AuthService]
});
----

We can then ask the `TestBed` to resolve a token into a dependency using its internal injector, like so:

[source,typescript]
----
testBedService = TestBed.get(AuthService);
----

If most of our test specs need the same dependency mocked the same way we can resolve it once in the `beforeEach` function and mock it it there.

== Resolving via the `inject` Function

[source,typescript]
----
it('Service injected via inject(...) and TestBed.get(...) should be the same instance',
    inject([AuthService], (injectService: AuthService) => {
      expect(injectService).toBe(testBedService);
    })
);
----

The `inject` function wraps the test spec function but lets us also _inject_ dependencies using the parent injector in the `TestBed`.

We use it like so:

[source,typescript]
----
inject(
  [token1, token2, token2],
  (dep1, dep2, dep3) => { }
)
----

The first param is an array of tokens we want to resolve dependencies for, the second parameter is a function whose arguments are the resolved dependencies.

Using the `inject` function:

* Makes it clear what dependencies each spec function uses.
* If each test spec requires different mocks and spies this is a better solution than resolving it once per test suite.

[IMPORTANT]
====
This will eventually move to becoming a function decorator like so:
 +
 +
[source,typescript]
----
@Inject (dep1: Token1, dep2: Token2) => { ... }
----
====

== Overriding the Component's Providers

_Before_ we create a component via the `TestBed` we can _override_ its providers. Let's imagine we have a mock `AuthService` like so:

[source,typescript]
----
class MockAuthService extends AuthService {
  isAuthenticated() {
    return 'Mocked';
  }
}
----

We can override the component's providers to use this mocked `AuthService` like so.

[source,typescript]
----
TestBed.overrideComponent(
    LoginComponent,
    {set: {providers: [{provide: AuthService, useClass: MockAuthService}]}}
);
----

The syntax is pretty specific, it's called a `MetaDataOverride` and it can have the properties `set`, `add` and `remove`. We use `set` to completely replace the providers array with the values we've set.


== Resolving via the Component's Injector

Now our component has been configured with its own providers it will therefore have a child injector.

When the component is created since it has its own injector it will resolve the `AuthService` itself and not forward the request to its parent `TestBed` injector.

If we wanted to get the _same_ instance of a dependency that was passed to the component's constructor we would need to resolve it using the component's injector. We can do that through the component fixture like so:

[source,typescript]
----
componentService = fixture.debugElement.injector.get(AuthService);
----

The above code resolves the token using the component's child injector.

== Summary

We can resolve dependencies in our tests using a number of methods.

We can resolve using the the test bed itself, usually in the `beforeEach` function and store the resolved dependencies for use in our test specs.

We can resolve using the `inject` function at the start of each test spec.

We can also override the default providers for our components using the `TestBed`.

We can then also use the component's _child injector_ to resolve tokens.

== Listing

.login.component.spec.ts
[source,typescript]
----
include::{sourcedir}/app/login.component.spec.ts[]
----
